### ISSUE TITLE
Multiple sensors

### ISSUE THREAD

**Issue by worldhugo** [mcc-robotics/sharp-distance#2]
Hi !

First, thanks for your work and explanations !

Do you think I can use your library for multiple sensors (10) and an Arduino Mega ? Any recommandations ?

Thanks !!!

**Comment by gberl001** [comment]
Hey, thanks for the feedback.

I think it would be possible so long as you don't want a super high resolution. To be honest it's been a long time since I last worked on this code so I had to look over it a bit but if I refreshed myself accurately I can give you some info on update times.

The default number of burst samples is 8
The default delay (BURST_DELAY_MICROS) is 1500 us

So, with the default you are looking at a maximum update of once every 8*1500=12000us or 12ms. The library isn't designed for multiple sensors so you can only take one sensor reading at a time. It could be optimized so you could read multiple sensors at the same time and get pretty fast update results.

All of that to say, if you take a reading from all ten sensors at once, and they all do their burst readings you'll only get about 9 readings from all sensors per second.

As far as recommendations... I personally really dislike the Sharp sensors, they're very unreliable but they are good in the sense that they have a relatively wide beam. I generally point people toward laser distance sensors. I'm not sure how software savvy you are but this laser sensor has a great range of 1-6000mm and it's very fast update rate at 100Hz (100 readings per second). [VL53L4CD](https://www.adafruit.com/product/5396). It has a fairly linear curve (meaning you don't need a fancy algorithm to convert the reading into an actual distance. The part where I say you may need to be software savvy is that it uses I2C communication. It connects using two wires but you can connect many devices (theoretically up to 127) but you have to change the address of the device.

Sorry for the length, I'd be happy to help you through the process if you have issues or need help getting started. Just keep chatting in this thread and I should get notified.

Thanks again for checking out my project.

**Comment by worldhugo** [comment]
Hey ! Thanks for your response !

Your library works perfect even with 10 sensors. Indeed there is a delay but not a problem for my application.

On the other hand, I still had a little noise, so I carried out a new filtering by taking the lowest value out of 5 readings: perfect !

Thanks again !

**Comment by gberl001** [comment]
I'm glad it worked out.
